#
# This is a modified version of zlib, which does all memory
# allocation ahead of time.
#
# This is the compression code, see zlib_inflate for the
# decompression code.
#

obj-y += sandtool.o

sandtool-objs := libconv.o libconv_syms.o
