#ifndef MX25KEYBOARD_GLOBAL_H
#define MX25KEYBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MX25KEYBOARD_LIBRARY)
#  define MX25KEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MX25KEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MX25KEYBOARD_GLOBAL_H
