

#ifndef		_QAPPCRYPT_H
#define		_QAPPCRYPT_H

#ifndef		QAPPCRYPT_DATA
#define		QAPPCRYPT_DATA	extern
#endif


#include	<QTermActAnalysis.h>
#include	<QDef.h>
#ifdef		__cplusplus
extern	"C"
{
#endif




#define			QSCRIPTNOTPERFORMED	0x00
#define			QSCRIPTPROCESSFAILED	0x01
#define			QSCRIPTPROCESSSUCCESS	0x02

#define			QADVICEREQUIRED			0x08
#define			QSERVICENOTALLOWED		0x01
#define			QPINTRYLIMITEXCEED		0x02
#define			QISSUERAUTHFAILED		0x03

#define			QARC_OFFLINEAPPROVED	"Y1"
#define			QARC_OFFLINEDECLINED	"Z1"
#define			QARC_REFERRALAPPROVED	"Y2"
#define			QARC_REFERRALDECLINED	"Z2"
#define			QARC_ONLINEFAILOFFLINEAPPROVED	"Y3"
#define			QARC_ONLINEFAILOFFLINEDECLINED	"Z3"

typedef		enum {QFIRSTGACPHASE,QSECONDGACPHASE}QGACPHASE;
typedef		struct
{
    UCHAR  	ucSeqNumber : 4,
            ucScriptResult : 4;
	UCHAR	aucScriptID[QSCRIPTIDLEN];
}QSCRIPTRESULT;

typedef		struct
{
	UCHAR	ucScriptTag;
	USHORT	uiScriptLen;
	UCHAR	aucScriptData[QMAXSCRIPTDATALEN];
}QISSURESCRIPT,*PQISSURESCRIPT;
QAPPCRYPT_DATA	UCHAR	QCDOL1Data[QMAXCDOLDATALEN];
QAPPCRYPT_DATA	UCHAR	QCDOL1DataLen;
QAPPCRYPT_DATA	UCHAR	QCDOL2Data[QMAXCDOLDATALEN];
QAPPCRYPT_DATA	UCHAR	QCDOL2DataLen;
QAPPCRYPT_DATA	UCHAR	QGACRespLen;
QAPPCRYPT_DATA	UCHAR	QGACRespData[QMAXGACDATALEN];
QAPPCRYPT_DATA	UCHAR	QIssureScriptNum;
QAPPCRYPT_DATA	QISSURESCRIPT	QIssureScript[QMAXSCRIPTNUMS];


UCHAR	QAPPCRYPT_CheckGACMandaData(UCHAR ucGACPHASE,BOOL bCDAFlag);
UCHAR	QAPPCRYPT_GenerateAC(UCHAR ucGACPHASE,QCRYPTTYPE reqCrypt,BOOL bCDAFlag);
UCHAR	QAPPCRYPT_OfflineProcess(QCRYPTTYPE reqCrypt);
UCHAR	QAPPCRYPT_ICTransDataPack(PUCHAR pTransDol,UCHAR ucTransDolLen,PUCHAR pTransDolData,USHORT *puiTransDolDataLen);
BOOL	QAPPCRYPT_CheckScriptValid(PUCHAR pScript,UCHAR ucScriptLen);
UCHAR	QAPPCRYPT_ScriptProcess(PUCHAR pScriptTag);
UCHAR	QAPPCRYPT_OnlineProcess(BOOL bConnectSuccess/*,UCHAR ucAuthRespCode,PUCHAR pICTransData,USHORT uiICTransDataLen*/);
UCHAR	QAPPCRYPT_GetGACData(PUCHAR	pIccData,USHORT uiDataLen);
UCHAR	QAPPCRYPT_OnlineRespDataProcess(PUCHAR pAuthCode,PUCHAR	pRespData,USHORT	uiRespDataLen);
UCHAR	QAPPCRIPT_AppendScript(UCHAR ucTag,PUCHAR pScriptData,USHORT uiScriptLen);

#ifdef		__cplusplus
}
#endif

#endif
