
#ifndef			_QVERIFY_H
#define			_QVERIFY_H

#ifndef			QVERIFY_DATA
#define			QVERIFY_DATA		extern
#endif

#include	<QTypeDef.h>
#ifdef __cplusplus
extern "C" {
#endif



#define			QVERIFYERR_SUCCESS				0
#define			QVERIFYERR_FAIL					1
#define			QVERIFYERR_PLAINPIN				2
#define			QVERIFYERR_ONLINEENPIN			3
#define			QVERIFYERR_PLAINPINANDSIGN		4
#define			QVERIFYERR_ENCIPHERPIN			5
#define			QVERIFYERR_ENCIPHERPINANDSIGN 6
#define			QVERIFYERR_SIGN					7
#define			QVERIFYERR_NOCVM				8
#define			QVERIFYERR_NOTMATCH				9
#define			QVERIFYERR_PARAM				10
#define			QVERIFYERR_MALFUNCTION			11
#define			QVERIFYERR_BYPASS				12
#define			QVERIFYERR_PINBLOCKED			13
#define			QVERIFYERR_LIMITEXCEEDED       14
#define			QVERIFYERR_CANCEL				15
#define			QVERIFYERR_PINNOTPRESENT		16
#define			QVERIFYERR_REVERIFY				17
#define			QVERIFYERR_ICCCOMMAND			18
#define			QVERIFYERR_UNRECOGNISED		19
#define			QVERIFYERR_ICCDATA				20
#define			QVERIFYERR_CONDITION			21
			
typedef		enum {QCVM_FAIL=0,QCVM_PLAINPIN,QCVM_ONLINEENCIPHERPIN,QCVM_PLAINPINANDSIGN,QCVM_ENCIPHER,
					QCVM_ENCIPHERANDSIGN,QCVM_SIGNATURE=0x1E,QCVM_NOCVM=0x1F,QCVM_IDCARD} QCVMMETHODCODE;

typedef		enum {QCONDITION_ALWAYS=0,QCONDITION_UNATTENDCASH,QCONDITION_NOTUHATTENDCASH,QCONDITION_SUPPORTCVM,
	                QCONDITION_MANUCASH,QCONDITION_PURCASHBACK,QCONDITION_UNDERX,QCONDITION_OVERX,QCONDITION_UNDERY,
	                QCONDITION_OVERY} QCONDITION;

#define			CVMRESULT_UNKNOWN			0x00
#define			CVMRESULT_FAILED			0x01
#define			CVMRESULT_SUCCESSFUL  	0x02

typedef		struct
{
	UCHAR	ucCVMCode;
	UCHAR	ucConditionCode;
	UCHAR	ucCVMResult;
		
}QCVMRESULT;

QVERIFY_DATA 	UINT	QCVM_X,QCVM_Y;
QVERIFY_DATA	UCHAR	QCVMPerformNums;
UCHAR	QVERIFY_PlainPIN();
UCHAR	QVERIFY_EncipherOnlinePIN(void);
UCHAR	QVERIFY_Signature(void);
BOOL	QVERIFY_CheckICCPinDataObject(void);
UCHAR	QVERIFY_ICCPinPKRecovery(void);
UCHAR	QVERIFY_ChooseICCPinPK(void);
UCHAR	QVERIFY_EncipherOfflinePIN(void);
UCHAR	QVERIFY_CVMProcess(QCVMMETHODCODE enCVMMethodCode);
UCHAR	QVERIFY_Process(void);
UCHAR	QVERIFY_IDCardVerify(void);
void	QVERIFY_RandNumGen(PUCHAR	pRandBuff,UCHAR ucMaxLengh);
UCHAR	QVERIFY_qVSDC(unsigned int uiAmount);

#ifdef __cplusplus
}
#endif
#endif




