
#ifndef			_EMVERROR_H
#define			_EMVERROR_H

#include		<TypeDef.h>

#define			EMVERROR_SUCCESS				0
#define			EMVERROR_FUNCNOTSUPPORT		1
#define			EMVERROR_CARDBLOCKED			2
#define			EMVERROR_PSENOTFIND			3
#define			EMVERROR_PSEBLOCKED			4
#define         EMVERROR_ICCCOMAND			5
#define			EMVERROR_ICCDATA				6
#define			EMVERROR_PARAM					7
#define			EMVERROR_MISSDATA				8
#define			EMVERROR_RESELECT				9
#define			EMVERROR_DATA					10
#define			EMVERROR_DATAAUTH				11
#define			EMVERROR_CAPKNOTFOUND			12
#define			EMVERROR_CERTIFICATIONMISS   13
#define			EMVERROR_CERTIFICATIONLEN	14
#define			EMVERROR_HASHVALUE			15
#define			EMVERROR_CAPKINDEXNOTFOUND   16
#define			EMVERROR_CANCEL				17
#define			EMVERROR_NEEDARQC				18
#define			EMVERROR_EXTERNALAUTH			19
#define			EMVERROR_ISSUREDATA			20
#define			EMVERROR_OPENCOM				21
#define			EMVERROR_SENDDATA				22
#define			EMVERROR_RECEIVEDATA			23
#define			EMVERROR_TAGNOTFIND			24
#define			EMVERROR_NOSUPPORTAPP			25
#define			EMVERROR_IPKREVOKE			26
#define			EMVERROR_PARAMUPDATE			27
#define			EMVERROR_VELOCITYCHECK		28
#define			EMVERROR_VERIFY				29
#define			EMVERROR_SAVEFILE				30
#define			EMVERROR_READFILE				31
#define			EMVERROR_WRITE					32
#define			EMVERROR_INVALIDSERVICE		33
#define			EMVERROR_SCRIPTLIMIT			34
#define			EMVERROR_CAPKINVALID			35
#define			EMVERROR_OVERFLOW				36
#define			EMVERROR_CID					37
#define			EMVERROR_DATE					38
#define			EMVERROR_RESPFORMAT			39
#define			EMVERROR_BYPASS				40
#define			EMVERROR_FALLBACK				41
#define			EMVERROR_APPBLOCKED			42
#define			EMVERROR_ISSUERREFERAL		43
typedef		struct
{
	UCHAR		ucMsgIndex;
	UCHAR		aucErrMsg[20];
}EMVERRMSG;

void 	EMVERROR_DisplayMsg(UCHAR	ucMsgId);

#endif
