/*
	Operating System
--------------------------------------------------------------------------
	FILE  osapi.h
--------------------------------------------------------------------------
    INTRODUCTION
    ============
    Created :		2002-10-03		Xiaoxi Jiang
    Last modified :	2002-10-03		Xiaoxi Jiang
    Module :
    Purpose :
        Header file.

    List of routines in file :

    File history :
*/

#ifndef __OSAPI_H
#define __OSAPI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <osevent.h>
#include <osmifare.h>
#include <type_uns.h> 
#include <oswifi.h>

typedef struct
{
	unsigned char ucMainVer;
	unsigned char ucSubVer;
	unsigned char aucName[16];
	/* Library Function */
	/* conv.c */
	void * (*pfnCONV_AscBcd)(unsigned char *pucDest, unsigned int uiDestLen,
					unsigned char *pucSrc, unsigned int uiSrcLen);
	void * (*pfnCONV_AscHex)(unsigned char *pucDest, unsigned int uiDestLen,
					unsigned char *pucSrc, unsigned int uiSrcLen);
	unsigned long (*pfnCONV_AscLong)(unsigned char *pucSrc,unsigned int iLen);
	void * (*pfnCONV_BcdAsc)(unsigned char *pucDest,unsigned char *pucSrc,int uiDestLen);
	unsigned long (*pfnCONV_BcdLong)(unsigned char *pucSrc,unsigned int uiSrcLen);
	void * (*pfnCONV_BcdStr)(unsigned char *pucDest,unsigned char *pucSrc,int uiDestLen);
	void * (*pfnCONV_CharAsc)(unsigned char *pucDest,unsigned char ucLen,unsigned char *pucSrc);
	void * (*pfnCONV_CharBcd)(unsigned char *pucDest,unsigned char ucLen,unsigned char *pucSrc);
	unsigned char (*pfnCONV_CharHex)(unsigned char ucCh);
	void * (*pfnCONV_CharStr)(unsigned char *pucDest,unsigned char ucLen,unsigned char *pucSrc);
	void * (*pfnCONV_HexAsc)(unsigned char *pucDest,unsigned char *pucSrc,unsigned int uiLen);
	void * (*pfnCONV_HexStr)(unsigned char *pucDest,unsigned char *pucSrc,unsigned int uiLen);
	unsigned long (*pfnCONV_HexLong)(unsigned char *pucSrc,unsigned int uiLen);
	void * (*pfnCONV_IntAsc)(unsigned char *pucDest,unsigned int uiLen,unsigned int *puiSrc);
	void * (*pfnCONV_IntBcd)(unsigned char *pucDest, unsigned int uiLen,unsigned int *puiSrc);
	void * (*pfnCONV_IntHex)(unsigned char *pucDest,unsigned int uiLen,unsigned int *puiSrc);
	void * (*pfnCONV_IntStr)(unsigned char *pucDest,unsigned int uiLen,unsigned int *puiSrc);
	void * (*pfnCONV_LongAsc)(unsigned char *pucDest,unsigned int uiLen,unsigned long *pulSrc);
	void * (*pfnCONV_LongBcd)(unsigned char *pucDest,unsigned int uiLen,unsigned long *pulSrc);
	void * (*pfnCONV_LongHex)(unsigned char *pucDest ,unsigned int uiLen,unsigned long *pulSrc);
	void * (*pfnCONV_LongStr)(unsigned char *pucDest,unsigned int uiLen,unsigned long *pulSrc);
	void * (*pfnCONV_ShortAsc)(unsigned char *pucDest,unsigned int uiLen,unsigned short *puiSrc);
	void * (*pfnCONV_ShortBcd)(unsigned char *pucDest,unsigned int uiLen,unsigned short *puiSrc);
	void * (*pfnCONV_ShortHex)(unsigned char *pucDest,unsigned int uiLen,unsigned short *puiSrc);
	void * (*pfnCONV_ShortStr)(unsigned char *pucDest,unsigned int uiLen,unsigned short *puiSrc);
	void * (*pfnCONV_StrBcd)(unsigned char *pucDest,unsigned int uiDestLen,unsigned char *pucSrc);
	void * (*pfnCONV_StrHex)(unsigned char *pucDest,unsigned int uiDestLen,unsigned char *pucSrc);
	unsigned long (*pfnCONV_StrLong)(unsigned char *pucSrc);
	void (*pfnCONV_StrLowCase)(char *pcStr);
	void (*pfnCONV_StrUpperCase)(char *pcStr);
	void (*pfnCONV_StrTrimRight)(char *pcStr,char cCh);
	void (*pfnCONV_StrTrimLeft)(char *pcStr,char cCh);
	void (*pfnCONV_Func00)(void);
	void (*pfnCONV_Func01)(void);
	void (*pfnCONV_Func02)(void);
	void (*pfnCONV_Func03)(void);
	void (*pfnCONV_Func04)(void);
	void (*pfnCONV_Func05)(void);
	void (*pfnCONV_Func06)(void);
	void (*pfnCONV_Func07)(void);
	void (*pfnCONV_Func08)(void);
	void (*pfnCONV_Func09)(void);
	void (*pfnCONV_Func10)(void);
	void (*pfnCONV_Func11)(void);
	void (*pfnCONV_Func12)(void);
	void (*pfnCONV_Func13)(void);
	void (*pfnCONV_Func14)(void);
	void (*pfnCONV_Func15)(void);
	void (*pfnCONV_Func16)(void);
	void (*pfnCONV_Func17)(void);
	void (*pfnCONV_Func18)(void);
	void (*pfnCONV_Func19)(void);
	void (*pfnCONV_Func20)(void);
	void (*pfnCONV_Func21)(void);
	void (*pfnCONV_Func22)(void);
	void (*pfnCONV_Func23)(void);
	void (*pfnCONV_Func24)(void);
	void (*pfnCONV_Func25)(void);
	void (*pfnCONV_Func26)(void);
	void (*pfnCONV_Func27)(void);
	void (*pfnCONV_Func28)(void);
	void (*pfnCONV_Func29)(void);
	void (*pfnCONV_Func30)(void);
	void (*pfnCONV_Func31)(void);
	void (*pfnCONV_Func32)(void);
	void (*pfnCONV_Func33)(void);
	void (*pfnCONV_Func34)(void);
	void (*pfnCONV_Func35)(void);
	void (*pfnCONV_Func36)(void);
	void (*pfnCONV_Func37)(void);
	void (*pfnCONV_Func38)(void);
	void (*pfnCONV_Func39)(void);
	void (*pfnCONV_Func40)(void);
	void (*pfnCONV_Func41)(void);
	void (*pfnCONV_Func42)(void);
	void (*pfnCONV_Func43)(void);
	void (*pfnCONV_Func44)(void);
	void (*pfnCONV_Func45)(void);
	void (*pfnCONV_Func46)(void);
	void (*pfnCONV_Func47)(void);
	void (*pfnCONV_Func48)(void);
	void (*pfnCONV_Func49)(void);
	/* crc.c */
	unsigned short (*pfnCRC_CalcSum16)(unsigned char *pucStart,unsigned char *pucEnd,unsigned short uiCRC);
	unsigned long (*pfnCRC_Calc32)(unsigned long ulCRC,const unsigned char *pucInData,unsigned long ulInLen);
	void (*pfnCRC_Func00)(void);
	void (*pfnCRC_Func01)(void);
	void (*pfnCRC_Func02)(void);
	void (*pfnCRC_Func03)(void);
	void (*pfnCRC_Func04)(void);
	void (*pfnCRC_Func05)(void);
	void (*pfnCRC_Func06)(void);
	void (*pfnCRC_Func07)(void);
	void (*pfnCRC_Func08)(void);
	void (*pfnCRC_Func09)(void);
	void (*pfnCRC_Func10)(void);
	void (*pfnCRC_Func11)(void);
	void (*pfnCRC_Func12)(void);
	void (*pfnCRC_Func13)(void);
	void (*pfnCRC_Func14)(void);
	void (*pfnCRC_Func15)(void);
	void (*pfnCRC_Func16)(void);
	void (*pfnCRC_Func17)(void);
	void (*pfnCRC_Func18)(void);
	void (*pfnCRC_Func19)(void);
	void (*pfnCRC_Func20)(void);
	void (*pfnCRC_Func21)(void);
	void (*pfnCRC_Func22)(void);
	void (*pfnCRC_Func23)(void);
	void (*pfnCRC_Func24)(void);
	void (*pfnCRC_Func25)(void);
	void (*pfnCRC_Func26)(void);
	void (*pfnCRC_Func27)(void);
	void (*pfnCRC_Func28)(void);
	void (*pfnCRC_Func29)(void);
	void (*pfnCRC_Func30)(void);
	void (*pfnCRC_Func31)(void);
	void (*pfnCRC_Func32)(void);
	void (*pfnCRC_Func33)(void);
	void (*pfnCRC_Func34)(void);
	void (*pfnCRC_Func35)(void);
	void (*pfnCRC_Func36)(void);
	void (*pfnCRC_Func37)(void);
	void (*pfnCRC_Func38)(void);
	void (*pfnCRC_Func39)(void);
	void (*pfnCRC_Func40)(void);
	void (*pfnCRC_Func41)(void);
	void (*pfnCRC_Func42)(void);
	void (*pfnCRC_Func43)(void);
	void (*pfnCRC_Func44)(void);
	void (*pfnCRC_Func45)(void);
	void (*pfnCRC_Func46)(void);
	void (*pfnCRC_Func47)(void);
	void (*pfnCRC_Func48)(void);
	void (*pfnCRC_Func49)(void);
	/* date.c */
	long (*pfnDATE_LeapYearStr)(char *pcDate);
	long (*pfnDATE_LeapYearInt)(int iYear);
	long (*pfnDATE_ValideDateStr)(char *pcDate);
	long (*pfnDATE_ValideDateInt)(int iYear,int iMonth,int iDay);
	long (*pfnDATE_ValideTimeStr)(char *pcTime);
	long (*pfnDATE_ValideTimeInt)(int iHour,int iMin,int iSec);
	long (*pfnDATE_ConvStrInt)(char *pcDate,int *piYear,int *piMonth,int *piDay);
	long (*pfnDATE_ConvIntStr)(int iYear,int iMonth,int iDay,char *pcDate);
	long (*pfnDATE_ConvStrLong)(char *pcDate,long *plDate);
	long (*pfnDATE_ConvLongStr)(long lDate,char *pcDate);
	long (*pfnDATE_MonthDaysStr)(char *pcDate, int *piDays );
	long (*pfnDATE_MonthDaysInt)(int iYear,int iMonth, int *piDays );
	long (*pfnDATE_YearDaysStr)(char *pcDate,int *piDays );
	long (*pfnDATE_YearDaysInt)(int iYear,int *piDays );
	long (*pfnDATE_OneYearDaysStr)(char *pcDate,int *piDays );
	long (*pfnDATE_DiffDaysStr)(char *pcDate1,char *pcDate2,long *plDays);
	long (*pfnDATE_WeekDayStr)(char *pcDate,int *piWeekDay);
	long (*pfnDATE_YearChangeStr)(char *pcDate,int iYear);
	long (*pfnDATE_MonthChangeStr)(char *pcDate,int iMonthChange);
	long (*pfnDATE_DayChangeStr)(char *pcDate,long lDayChange);
	long (*pfnDATE_ConvDateNameStr)(char *pcDate1,char *pcDate2);
	void (*pfnDATE_Func01)(void);
	void (*pfnDATE_Func02)(void);
	void (*pfnDATE_Func03)(void);
	void (*pfnDATE_Func04)(void);
	void (*pfnDATE_Func05)(void);
	void (*pfnDATE_Func06)(void);
	void (*pfnDATE_Func07)(void);
	void (*pfnDATE_Func08)(void);
	void (*pfnDATE_Func09)(void);
	void (*pfnDATE_Func10)(void);
	void (*pfnDATE_Func11)(void);
	void (*pfnDATE_Func12)(void);
	void (*pfnDATE_Func13)(void);
	void (*pfnDATE_Func14)(void);
	void (*pfnDATE_Func15)(void);
	void (*pfnDATE_Func16)(void);
	void (*pfnDATE_Func17)(void);
	void (*pfnDATE_Func18)(void);
	void (*pfnDATE_Func19)(void);
	void (*pfnDATE_Func20)(void);
	void (*pfnDATE_Func21)(void);
	void (*pfnDATE_Func22)(void);
	void (*pfnDATE_Func23)(void);
	void (*pfnDATE_Func24)(void);
	void (*pfnDATE_Func25)(void);
	void (*pfnDATE_Func26)(void);
	void (*pfnDATE_Func27)(void);
	void (*pfnDATE_Func28)(void);
	void (*pfnDATE_Func29)(void);
	void (*pfnDATE_Func30)(void);
	void (*pfnDATE_Func31)(void);
	void (*pfnDATE_Func32)(void);
	void (*pfnDATE_Func33)(void);
	void (*pfnDATE_Func34)(void);
	void (*pfnDATE_Func35)(void);
	void (*pfnDATE_Func36)(void);
	void (*pfnDATE_Func37)(void);
	void (*pfnDATE_Func38)(void);
	void (*pfnDATE_Func39)(void);
	void (*pfnDATE_Func40)(void);
	void (*pfnDATE_Func41)(void);
	void (*pfnDATE_Func42)(void);
	void (*pfnDATE_Func43)(void);
	void (*pfnDATE_Func44)(void);
	void (*pfnDATE_Func45)(void);
	void (*pfnDATE_Func46)(void);
	void (*pfnDATE_Func47)(void);
	void (*pfnDATE_Func48)(void);
	void (*pfnDATE_Func49)(void);
	/* algo.c */
    void (*pfnMD5_Compute)(unsigned char *pucInData,unsigned int uiInLen,unsigned char *pucDigest);
    void (*pfnSHA1_Compute)(unsigned char *pucInData,unsigned int uiInLen,unsigned char *pucDigest);
	void (*pfnALGO_Func02)(void);
	void (*pfnALGO_Func03)(void);
	void (*pfnALGO_Func04)(void);
	void (*pfnALGO_Func05)(void);
	void (*pfnALGO_Func06)(void);
	void (*pfnALGO_Func07)(void);
	void (*pfnALGO_Func08)(void);
	void (*pfnALGO_Func09)(void);
	unsigned char (*pfnRSA_PublicEncrypt)(void);
    unsigned char (*pfnRSA_PublicDecrypt)(unsigned char *pucPublicKey,unsigned int uiPublicKeyLen,
					unsigned char *pucPublicKeyExp,unsigned int uiPublicKeyExpLen,
					unsigned char *pucIn,unsigned int uiInLen,
					unsigned char *pucOut);
	unsigned char (*pfnRSA_PrivateEncrypt)(void);
	unsigned char (*pfnRSA_PrivateDecrypt)(void);
	void (*pfnALGO_Func14)(void);
	void (*pfnALGO_Func15)(void);
	void (*pfnALGO_Func16)(void);
	void (*pfnALGO_Func17)(void);
	void (*pfnALGO_Func18)(void);
	void (*pfnALGO_Func19)(void);
	void (*pfnALGO_Func20)(void);
	void (*pfnALGO_Func21)(void);
	void (*pfnALGO_Func22)(void);
	void (*pfnALGO_Func23)(void);
	void (*pfnALGO_Func24)(void);
	void (*pfnALGO_Func25)(void);
	void (*pfnALGO_Func26)(void);
	void (*pfnALGO_Func27)(void);
	void (*pfnALGO_Func28)(void);
	void (*pfnALGO_Func29)(void);
	void (*pfnALGO_Func30)(void);
	void (*pfnALGO_Func31)(void);
	void (*pfnALGO_Func32)(void);
	void (*pfnALGO_Func33)(void);
	void (*pfnALGO_Func34)(void);
	void (*pfnALGO_Func35)(void);
	void (*pfnALGO_Func36)(void);
	void (*pfnALGO_Func37)(void);
	void (*pfnALGO_Func38)(void);
	void (*pfnALGO_Func39)(void);
	void (*pfnALGO_Func40)(void);
	void (*pfnALGO_Func41)(void);
	void (*pfnALGO_Func42)(void);
	void (*pfnALGO_Func43)(void);
	void (*pfnALGO_Func44)(void);
	void (*pfnALGO_Func45)(void);
	void (*pfnALGO_Func46)(void);
	void (*pfnALGO_Func47)(void);
	void (*pfnALGO_Func48)(void);
	void (*pfnALGO_Func49)(void);
	void (*pfnALGO_Func50)(void);
	void (*pfnALGO_Func51)(void);
	void (*pfnALGO_Func52)(void);
	void (*pfnALGO_Func53)(void);
	void (*pfnALGO_Func54)(void);
	void (*pfnALGO_Func55)(void);
	void (*pfnALGO_Func56)(void);
	void (*pfnALGO_Func57)(void);
	void (*pfnALGO_Func58)(void);
	void (*pfnALGO_Func59)(void);
	void (*pfnALGO_Func60)(void);
	void (*pfnALGO_Func61)(void);
	void (*pfnALGO_Func62)(void);
	void (*pfnALGO_Func63)(void);
	void (*pfnALGO_Func64)(void);
	void (*pfnALGO_Func65)(void);
	void (*pfnALGO_Func66)(void);
	void (*pfnALGO_Func67)(void);
	void (*pfnALGO_Func68)(void);
	void (*pfnALGO_Func69)(void);
	void (*pfnALGO_Func70)(void);
	void (*pfnALGO_Func71)(void);
	void (*pfnALGO_Func72)(void);
	void (*pfnALGO_Func73)(void);
	void (*pfnALGO_Func74)(void);
	void (*pfnALGO_Func75)(void);
	void (*pfnALGO_Func76)(void);
	void (*pfnALGO_Func77)(void);
	void (*pfnALGO_Func78)(void);
	void (*pfnALGO_Func79)(void);
	void (*pfnALGO_Func80)(void);
	void (*pfnALGO_Func81)(void);
	void (*pfnALGO_Func82)(void);
	void (*pfnALGO_Func83)(void);
	void (*pfnALGO_Func84)(void);
	void (*pfnALGO_Func85)(void);
	void (*pfnALGO_Func86)(void);
	void (*pfnALGO_Func87)(void);
	void (*pfnALGO_Func88)(void);
	void (*pfnALGO_Func89)(void);
	void (*pfnALGO_Func90)(void);
	void (*pfnALGO_Func91)(void);
	void (*pfnALGO_Func92)(void);
	void (*pfnALGO_Func93)(void);
	void (*pfnALGO_Func94)(void);
	void (*pfnALGO_Func95)(void);
	void (*pfnALGO_Func96)(void);
	void (*pfnALGO_Func97)(void);
	void (*pfnALGO_Func98)(void);
	void (*pfnALGO_Func99)(void);
	/* util.c */
	void (*pfnUTIL_Func00)(void);
	void (*pfnUTIL_Func01)(void);
	void (*pfnUTIL_Func02)(void);
	void (*pfnUTIL_Func03)(void);
	void (*pfnUTIL_Func04)(void);
	void (*pfnUTIL_Func05)(void);
	void (*pfnUTIL_Func06)(void);
	void (*pfnUTIL_Func07)(void);
	void (*pfnUTIL_Func08)(void);
	void (*pfnUTIL_Func09)(void);
	void (*pfnUTIL_Func10)(void);
	void (*pfnUTIL_Func11)(void);
	void (*pfnUTIL_Func12)(void);
	void (*pfnUTIL_Func13)(void);
	void (*pfnUTIL_Func14)(void);
	void (*pfnUTIL_Func15)(void);
	void (*pfnUTIL_Func16)(void);
	void (*pfnUTIL_Func17)(void);
	void (*pfnUTIL_Func18)(void);
	void (*pfnUTIL_Func19)(void);
	void (*pfnUTIL_Func20)(void);
	void (*pfnUTIL_Func21)(void);
	void (*pfnUTIL_Func22)(void);
	void (*pfnUTIL_Func23)(void);
	void (*pfnUTIL_Func24)(void);
	void (*pfnUTIL_Func25)(void);
	void (*pfnUTIL_Func26)(void);
	void (*pfnUTIL_Func27)(void);
	void (*pfnUTIL_Func28)(void);
	void (*pfnUTIL_Func29)(void);
	void (*pfnUTIL_Func30)(void);
	void (*pfnUTIL_Func31)(void);
	void (*pfnUTIL_Func32)(void);
	void (*pfnUTIL_Func33)(void);
	void (*pfnUTIL_Func34)(void);
	void (*pfnUTIL_Func35)(void);
	void (*pfnUTIL_Func36)(void);
	void (*pfnUTIL_Func37)(void);
	void (*pfnUTIL_Func38)(void);
	void (*pfnUTIL_Func39)(void);
	void (*pfnUTIL_Func40)(void);
	void (*pfnUTIL_Func41)(void);
	void (*pfnUTIL_Func42)(void);
	void (*pfnUTIL_Func43)(void);
	void (*pfnUTIL_Func44)(void);
	void (*pfnUTIL_Func45)(void);
	void (*pfnUTIL_Func46)(void);
	void (*pfnUTIL_Func47)(void);
	void (*pfnUTIL_Func48)(void);
	void (*pfnUTIL_Func49)(void);
	void (*pfnUTIL_Func50)(void);
	void (*pfnUTIL_Func51)(void);
	void (*pfnUTIL_Func52)(void);
	void (*pfnUTIL_Func53)(void);
	void (*pfnUTIL_Func54)(void);
	void (*pfnUTIL_Func55)(void);
	void (*pfnUTIL_Func56)(void);
	void (*pfnUTIL_Func57)(void);
	void (*pfnUTIL_Func58)(void);
	void (*pfnUTIL_Func59)(void);
	void (*pfnUTIL_Func60)(void);
	void (*pfnUTIL_Func61)(void);
	void (*pfnUTIL_Func62)(void);
	void (*pfnUTIL_Func63)(void);
	void (*pfnUTIL_Func64)(void);
	void (*pfnUTIL_Func65)(void);
	void (*pfnUTIL_Func66)(void);
	void (*pfnUTIL_Func67)(void);
	void (*pfnUTIL_Func68)(void);
	void (*pfnUTIL_Func69)(void);
	void (*pfnUTIL_Func70)(void);
	void (*pfnUTIL_Func71)(void);
	void (*pfnUTIL_Func72)(void);
	void (*pfnUTIL_Func73)(void);
	void (*pfnUTIL_Func74)(void);
	void (*pfnUTIL_Func75)(void);
	void (*pfnUTIL_Func76)(void);
	void (*pfnUTIL_Func77)(void);
	void (*pfnUTIL_Func78)(void);
	void (*pfnUTIL_Func79)(void);
	void (*pfnUTIL_Func80)(void);
	void (*pfnUTIL_Func81)(void);
	void (*pfnUTIL_Func82)(void);
	void (*pfnUTIL_Func83)(void);
	void (*pfnUTIL_Func84)(void);
	void (*pfnUTIL_Func85)(void);
	void (*pfnUTIL_Func86)(void);
	void (*pfnUTIL_Func87)(void);
	void (*pfnUTIL_Func88)(void);
	void (*pfnUTIL_Func89)(void);
	unsigned char (*pfnOSMENU_MainForApp)(void);
	CONFIG_PARAM (*pfnOSCFG_ReadParam)(void);
	unsigned char (*pfnOSCFG_SetETHConfig)(unsigned char *paucAddr,unsigned char *paucMask,unsigned char *paucGatewayAddr);
	void (*pfnUTIL_Func93)(void);
	void (*pfnUTIL_Func94)(void);
	void (*pfnUTIL_Func95)(void);
	void (*pfnUTIL_Func96)(void);
	void (*pfnUTIL_Func97)(void);
	/* DRIVER Function: 5 */
	DRV_OUT * (*pfnOSDRV_CallAsync)(DRIVER *pDrv);
	unsigned char (*pfnOSDRV_Ioctl)(unsigned char ucDrvID,unsigned char ucType,unsigned char *pucData);
	unsigned char (*pfnOSDRV_Wait)(DRV_OUT *pDrvOut);
	void (*pfnOSDRV_Abort)(unsigned char ucDrvID);
	void (*pfnOSDRV_Call)(DRIVER *pDrv);
	/* MMI Function: 15 */
	void (*pfnOSMMI_ClrDisplay)(unsigned char ucFont,unsigned char ucRow);
	void (*pfnOSMMI_Beep)(void);
	DRV_OUT * (*pfnOSMMI_GetKey)(void);
	unsigned char (*pfnOSMMI_XGetKey)(void);
	DRV_OUT * (*pfnOSMMI_GetKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	unsigned char * (*pfnOSMMI_XGetKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	DRV_OUT * (*pfnOSMMI_GetFixKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	unsigned char * (*pfnOSMMI_XGetFixKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	DRV_OUT * (*pfnOSMMI_GetPin)(unsigned char ucRow,unsigned char ucCol, unsigned char *pucPtr, unsigned char ucCharNB);
	unsigned char * (*pfnOSMMI_XGetPin)(unsigned char ucRow,unsigned char ucCol, unsigned char *pucPtr, unsigned char ucCharNB);
	void (*pfnOSMMI_Crypt)(unsigned char *pucCryptKey);
	void (*pfnOSMMI_DisplayASCII)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr);
	unsigned char (*pfnOSMMI_BackLightCtl)(unsigned char ucFlag);
	unsigned char (*pfnOSMMI_GB2312Display)(unsigned char ucFont,unsigned char ucRow, unsigned char ucCol, unsigned char *pucPtr);
	unsigned char (*pfnOSMMI_GraphDisplay)(unsigned char ucType,unsigned char ucRow, unsigned char ucCol, unsigned char *pucPtr,unsigned char ucLen);
	unsigned char (*pfnOSMMI_NonStdDisplay)(unsigned char ucFont,unsigned char ucRow, unsigned char ucCol, unsigned char *pucPtr);
	void (*pfnOSMMI_Func01)(void);
	void (*pfnOSMMI_Func02)(void);
	void (*pfnOSMMI_Func03)(void);
	void (*pfnOSMMI_Func04)(void);
	void (*pfnOSMMI_Func05)(void);
	void (*pfnOSMMI_Func06)(void);
	void (*pfnOSMMI_Func07)(void);
	void (*pfnOSMMI_Func08)(void);
	void (*pfnOSMMI_Func09)(void);
	void (*pfnOSMMI_Func10)(void);
	void (*pfnOSMMI_Func11)(void);
	void (*pfnOSMMI_Func12)(void);
	void (*pfnOSMMI_Func13)(void);
	void (*pfnOSMMI_Func14)(void);
	void (*pfnOSMMI_Func15)(void);
	void (*pfnOSMMI_Func16)(void);
	void (*pfnOSMMI_Func17)(void);
	void (*pfnOSMMI_Func18)(void);
	void (*pfnOSMMI_Func19)(void);
	void (*pfnOSMMI_Func20)(void);
	void (*pfnOSMMI_Func21)(void);
	void (*pfnOSMMI_Func22)(void);
	void (*pfnOSMMI_Func23)(void);
	void (*pfnOSMMI_Func24)(void);
	void (*pfnOSMMI_Func25)(void);
	void (*pfnOSMMI_Func26)(void);
	void (*pfnOSMMI_Func27)(void);
	void (*pfnOSMMI_Func28)(void);
	void (*pfnOSMMI_Func29)(void);
	void (*pfnOSMMI_Func30)(void);
	void (*pfnOSMMI_Func31)(void);
	void (*pfnOSMMI_Func32)(void);
	void (*pfnOSMMI_Func33)(void);
	void (*pfnOSMMI_Func34)(void);
	void (*pfnOSMMI_Func35)(void);
	void (*pfnOSMMI_Func36)(void);
	void (*pfnOSMMI_Func37)(void);
	void (*pfnOSMMI_Func38)(void);
	void (*pfnOSMMI_Func39)(void);
	void (*pfnOSMMI_Func40)(void);
	void (*pfnOSMMI_Func41)(void);
	void (*pfnOSMMI_Func42)(void);
	void (*pfnOSMMI_Func43)(void);
	void (*pfnOSMMI_Func44)(void);
	void (*pfnOSMMI_Func45)(void);
	void (*pfnOSMMI_Func46)(void);
	void (*pfnOSMMI_Func47)(void);
	void (*pfnOSMMI_Func48)(void);
	void (*pfnOSMMI_Func49)(void);
	/* PAD Function: 15 */
	void (*pfnOSPAD_ClrDisplay)(unsigned char ucFont,unsigned char ucRow);
	void (*pfnOSPAD_Beep)(void);
	DRV_OUT * (*pfnOSPAD_GetKey)(void);
	unsigned char (*pfnOSPAD_XGetKey)(void);
	DRV_OUT * (*pfnOSPAD_GetKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	unsigned char * (*pfnOSPAD_XGetKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	DRV_OUT * (*pfnOSPAD_GetFixKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	unsigned char * (*pfnOSPAD_XGetFixKeys)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr, unsigned char ucCharNB);
	DRV_OUT * (*pfnOSPAD_GetPin)(unsigned char ucRow,unsigned char ucCol, unsigned char *pucPtr, unsigned char ucCharNB);
	unsigned char * (*pfnOSPAD_XGetPin)(unsigned char ucRow,unsigned char ucCol, unsigned char *pucPtr, unsigned char ucCharNB);
	void (*pfnOSPAD_Crypt)(unsigned char *pucCryptKey);
	void (*pfnOSPAD_DisplayASCII)(unsigned char ucFont,unsigned char ucRow,unsigned char ucCol,unsigned char *pucPtr);
	unsigned char (*pfnOSPAD_BackLightCtl)(unsigned char ucFlag);
	unsigned char (*pfnOSPAD_GB2312Display)(unsigned char ucFont,unsigned char ucRow, unsigned char ucCol, unsigned char *pucPtr);
	unsigned char (*pfnOSPAD_GraphDisplay)(unsigned char ucType,unsigned char ucRow, unsigned char ucCol, unsigned char *pucPtr,unsigned char ucLen);
	void (*pfnOSPAD_Func00)(void);
	void (*pfnOSPAD_Func01)(void);
	void (*pfnOSPAD_Func02)(void);
	void (*pfnOSPAD_Func03)(void);
	void (*pfnOSPAD_Func04)(void);
	void (*pfnOSPAD_Func05)(void);
	void (*pfnOSPAD_Func06)(void);
	void (*pfnOSPAD_Func07)(void);
	void (*pfnOSPAD_Func08)(void);
	void (*pfnOSPAD_Func09)(void);
	void (*pfnOSPAD_Func10)(void);
	void (*pfnOSPAD_Func11)(void);
	void (*pfnOSPAD_Func12)(void);
	void (*pfnOSPAD_Func13)(void);
	void (*pfnOSPAD_Func14)(void);
	void (*pfnOSPAD_Func15)(void);
	void (*pfnOSPAD_Func16)(void);
	void (*pfnOSPAD_Func17)(void);
	void (*pfnOSPAD_Func18)(void);
	void (*pfnOSPAD_Func19)(void);
	void (*pfnOSPAD_Func20)(void);
	void (*pfnOSPAD_Func21)(void);
	void (*pfnOSPAD_Func22)(void);
	void (*pfnOSPAD_Func23)(void);
	void (*pfnOSPAD_Func24)(void);
	void (*pfnOSPAD_Func25)(void);
	void (*pfnOSPAD_Func26)(void);
	void (*pfnOSPAD_Func27)(void);
	void (*pfnOSPAD_Func28)(void);
	void (*pfnOSPAD_Func29)(void);
	void (*pfnOSPAD_Func30)(void);
	void (*pfnOSPAD_Func31)(void);
	void (*pfnOSPAD_Func32)(void);
	void (*pfnOSPAD_Func33)(void);
	void (*pfnOSPAD_Func34)(void);
	void (*pfnOSPAD_Func35)(void);
	void (*pfnOSPAD_Func36)(void);
	void (*pfnOSPAD_Func37)(void);
	void (*pfnOSPAD_Func38)(void);
	void (*pfnOSPAD_Func39)(void);
	void (*pfnOSPAD_Func40)(void);
	void (*pfnOSPAD_Func41)(void);
	void (*pfnOSPAD_Func42)(void);
	void (*pfnOSPAD_Func43)(void);
	void (*pfnOSPAD_Func44)(void);
	void (*pfnOSPAD_Func45)(void);
	void (*pfnOSPAD_Func46)(void);
	/* Printer Function: */
	unsigned char (*pfnOSPRN_BeginPrint)(unsigned char *pucParam);
	unsigned char (*pfnOSPRN_EndPrint)(void);
	unsigned char (*pfnOSPRN_CheckPaper)(unsigned char ucFlag);
	DRV_OUT * (*pfnOSPRN_PrintASCII)(unsigned char ucFont,unsigned char *pucPtr);
	DRV_OUT * (*pfnOSPRN_Feed)(unsigned char ucLineNB);
	unsigned char (*pfnOSPRN_XPrintASCII)(unsigned char ucFont,unsigned char *pucPtr);
	unsigned char (*pfnOSPRN_XFeed)(unsigned char ucLineNB);
	unsigned char (*pfnOSPRN_XPrintGB2312)(unsigned char ucASCFont,unsigned char ucGBFont,unsigned char *pucPtr);
	unsigned char (*pfnOSPRN_XPrintGraph)(unsigned char *pucInData,unsigned char ucInLen);
	DRV_OUT * (*pfnOSPRN_ReverseFeed)(unsigned char ucLineNB);
	unsigned char (*pfnOSPRN_XReverseFeed)(unsigned char ucLineNB);
	unsigned char (*pfnOSPRN_XPrintNonStd)(unsigned char ucFont,unsigned char *pucPtr);
	void (*pfnOSPRN_Func04)(void);
	void (*pfnOSPRN_Func05)(void);
	void (*pfnOSPRN_Func06)(void);
	void (*pfnOSPRN_Func07)(void);
	void (*pfnOSPRN_Func08)(void);
	void (*pfnOSPRN_Func09)(void);
	void (*pfnOSPRN_Func10)(void);
	void (*pfnOSPRN_Func11)(void);
	void (*pfnOSPRN_Func12)(void);
	void (*pfnOSPRN_Func13)(void);
	void (*pfnOSPRN_Func14)(void);
	void (*pfnOSPRN_Func15)(void);
	void (*pfnOSPRN_Func16)(void);
	void (*pfnOSPRN_Func17)(void);
	void (*pfnOSPRN_Func18)(void);
	void (*pfnOSPRN_Func19)(void);
	void (*pfnOSPRN_Func20)(void);
	void (*pfnOSPRN_Func21)(void);
	void (*pfnOSPRN_Func22)(void);
	void (*pfnOSPRN_Func23)(void);
	void (*pfnOSPRN_Func24)(void);
	void (*pfnOSPRN_Func25)(void);
	void (*pfnOSPRN_Func26)(void);
	void (*pfnOSPRN_Func27)(void);
	void (*pfnOSPRN_Func28)(void);
	void (*pfnOSPRN_Func29)(void);
	void (*pfnOSPRN_Func30)(void);
	void (*pfnOSPRN_Func31)(void);
	void (*pfnOSPRN_Func32)(void);
	void (*pfnOSPRN_Func33)(void);
	void (*pfnOSPRN_Func34)(void);
	void (*pfnOSPRN_Func35)(void);
	void (*pfnOSPRN_Func36)(void);
	void (*pfnOSPRN_Func37)(void);
	void (*pfnOSPRN_Func38)(void);
	void (*pfnOSPRN_Func39)(void);
	void (*pfnOSPRN_Func40)(void);
	void (*pfnOSPRN_Func41)(void);
	void (*pfnOSPRN_Func42)(void);
	void (*pfnOSPRN_Func43)(void);
	void (*pfnOSPRN_Func44)(void);
	void (*pfnOSPRN_Func45)(void);
	void (*pfnOSPRN_Func46)(void);
	void (*pfnOSPRN_Func47)(void);
	void (*pfnOSPRN_Func48)(void);
	void (*pfnOSPRN_Func49)(void);
	/* MAG Function: 1 */
	DRV_OUT * (*pfnOSMAG_Read)(void);
    DRV_OUT * (*pfnOSMAG_ReadGeneral)(unsigned char ucTrack1Method,
                unsigned char ucTrack2Method,
                unsigned char ucTrack3Method);
	void (*pfnOSMAG_Func01)(void);
	void (*pfnOSMAG_Func02)(void);
	void (*pfnOSMAG_Func03)(void);
	void (*pfnOSMAG_Func04)(void);
	void (*pfnOSMAG_Func05)(void);
	void (*pfnOSMAG_Func06)(void);
	void (*pfnOSMAG_Func07)(void);
	void (*pfnOSMAG_Func08)(void);
	void (*pfnOSMAG_Func09)(void);
	/* ICC Function: 7 */
	unsigned char (*pfnOSICC_Detect)(unsigned char ucReader);
	ICC_ANSWER * (*pfnOSICC_Command)(unsigned char ucReader,ICC_ORDER *pOrder);
	DRV_OUT * (*pfnOSICC_Insert)(void);
	DRV_OUT * (*pfnOSICC_OrderAsync)(unsigned char *pucOrder,unsigned short uiLen);
	DRV_OUT * (*pfnOSICC_Order)(DRV_IN  *pDrvIn);
	void (*pfnOSICC_Remove)(void);
	void (*pfnOSICC_PowerOff)(void);
	void (*pfnOSICC_Func00)(void);
	void (*pfnOSICC_Func01)(void);
	void (*pfnOSICC_Func02)(void);
	void (*pfnOSICC_Func03)(void);
	void (*pfnOSICC_Func04)(void);
	void (*pfnOSICC_Func05)(void);
	void (*pfnOSICC_Func06)(void);
	void (*pfnOSICC_Func07)(void);
	void (*pfnOSICC_Func08)(void);
	void (*pfnOSICC_Func09)(void);
	void (*pfnOSICC_Func10)(void);
	void (*pfnOSICC_Func11)(void);
	void (*pfnOSICC_Func12)(void);
	void (*pfnOSICC_Func13)(void);
	void (*pfnOSICC_Func14)(void);
	void (*pfnOSICC_Func15)(void);
	void (*pfnOSICC_Func16)(void);
	void (*pfnOSICC_Func17)(void);
	void (*pfnOSICC_Func18)(void);
	void (*pfnOSICC_Func19)(void);
	void (*pfnOSICC_Func20)(void);
	void (*pfnOSICC_Func21)(void);
	void (*pfnOSICC_Func22)(void);
	void (*pfnOSICC_Func23)(void);
	void (*pfnOSICC_Func24)(void);
	void (*pfnOSICC_Func25)(void);
	void (*pfnOSICC_Func26)(void);
	void (*pfnOSICC_Func27)(void);
	void (*pfnOSICC_Func28)(void);
	void (*pfnOSICC_Func29)(void);
	void (*pfnOSICC_Func30)(void);
	void (*pfnOSICC_Func31)(void);
	void (*pfnOSICC_Func32)(void);
	void (*pfnOSICC_Func33)(void);
	void (*pfnOSICC_Func34)(void);
	void (*pfnOSICC_Func35)(void);
	void (*pfnOSICC_Func36)(void);
	void (*pfnOSICC_Func37)(void);
	void (*pfnOSICC_Func38)(void);
	void (*pfnOSICC_Func39)(void);
	void (*pfnOSICC_Func40)(void);
	void (*pfnOSICC_Func41)(void);
	void (*pfnOSICC_Func42)(void);
	void (*pfnOSICC_Func43)(void);
	void (*pfnOSICC_Func44)(void);
	void (*pfnOSICC_Func45)(void);
	void (*pfnOSICC_Func46)(void);
	void (*pfnOSICC_Func47)(void);
	void (*pfnOSICC_Func48)(void);
	void (*pfnOSICC_Func49)(void);
	/* UART Function: */
	unsigned char (*pfnOSUART_Init1)(COM_PARAM *pComParam);
	unsigned char (*pfnOSUART_TxChar1)(unsigned char ucCh);
	unsigned short (*pfnOSUART_RxChar1)(unsigned short uiTimeout);
	void (*pfnOSUART_Flush1)(unsigned short uiLen);
	void (*pfnOSUART_Close1)(void);
	unsigned char (*pfnOSUART_Init2)(unsigned short uiParam1,unsigned short uiParam2,unsigned char ucParam3);
	void (*pfnOSUART_TxChar2)(unsigned char ucCh);
	unsigned short (*pfnOSUART_RxChar2)(unsigned short uiTimeout);
	void (*pfnOSUART_Close2)(void);
	void (*pfnOSUART_Func00)(void);
	void (*pfnOSUART_Func01)(void);
	void (*pfnOSUART_Func02)(void);
	void (*pfnOSUART_Func03)(void);
	void (*pfnOSUART_Func04)(void);
	void (*pfnOSUART_Func05)(void);
	void (*pfnOSUART_Func06)(void);
	void (*pfnOSUART_Func07)(void);
	void (*pfnOSUART_Func08)(void);
	void (*pfnOSUART_Func09)(void);
	void (*pfnOSUART_Func10)(void);
	void (*pfnOSUART_Func11)(void);
	void (*pfnOSUART_Func12)(void);
	void (*pfnOSUART_Func13)(void);
	void (*pfnOSUART_Func14)(void);
	void (*pfnOSUART_Func15)(void);
	void (*pfnOSUART_Func16)(void);
	void (*pfnOSUART_Func17)(void);
	void (*pfnOSUART_Func18)(void);
	void (*pfnOSUART_Func19)(void);
	void (*pfnOSUART_Func20)(void);
	void (*pfnOSUART_Func21)(void);
	void (*pfnOSUART_Func22)(void);
	void (*pfnOSUART_Func23)(void);
	void (*pfnOSUART_Func24)(void);
	void (*pfnOSUART_Func25)(void);
	void (*pfnOSUART_Func26)(void);
	void (*pfnOSUART_Func27)(void);
	void (*pfnOSUART_Func28)(void);
	void (*pfnOSUART_Func29)(void);
	void (*pfnOSUART_Func30)(void);
	void (*pfnOSUART_Func31)(void);
	void (*pfnOSUART_Func32)(void);
	void (*pfnOSUART_Func33)(void);
	void (*pfnOSUART_Func34)(void);
	void (*pfnOSUART_Func35)(void);
	void (*pfnOSUART_Func36)(void);
	void (*pfnOSUART_Func37)(void);
	void (*pfnOSUART_Func38)(void);
	void (*pfnOSUART_Func39)(void);
	void (*pfnOSUART_Func40)(void);
	void (*pfnOSUART_Func41)(void);
	void (*pfnOSUART_Func42)(void);
	void (*pfnOSUART_Func43)(void);
	void (*pfnOSUART_Func44)(void);
	void (*pfnOSUART_Func45)(void);
	void (*pfnOSUART_Func46)(void);
	void (*pfnOSUART_Func47)(void);
	void (*pfnOSUART_Func48)(void);
	void (*pfnOSUART_Func49)(void);
	/* MODEM Function: */
	unsigned char (*pfnOSMODEM_Dial)(DIAL_PARAM * pDialParam);
	unsigned char (*pfnOSMODEM_BackDial)(DIAL_PARAM * pDialParam);
	unsigned char (*pfnOSMODEM_CheckBackDial)(unsigned short uiTimeout);
	void (*pfnOSMODEM_ReadDialParam)(DIAL_PARAM * pDialParam);
	unsigned char (*pfnOSMODEM_SetParam)(unsigned char ucParamNb, unsigned char ucValue);
	void (*pfnOSMODEM_Func00)(void);
	void (*pfnOSMODEM_Func01)(void);
	void (*pfnOSMODEM_Func02)(void);
	void (*pfnOSMODEM_Func03)(void);
	void (*pfnOSMODEM_Func04)(void);
	void (*pfnOSMODEM_Func05)(void);
	void (*pfnOSMODEM_Func06)(void);
	void (*pfnOSMODEM_Func07)(void);
	void (*pfnOSMODEM_Func08)(void);
	/* MODEM PPP Function */
	unsigned char   (*pfnOSMODEMPPP_Open)(unsigned char* paucUserName,unsigned char *paucPassword);
	unsigned char	(*pfnOSMODEMPPP_Close)(void);
	unsigned char	(*pfnOSMODEMPPP_Check)(void);
	void (*pfnOSMODEM_Func12)(void);
	void (*pfnOSMODEM_Func13)(void);
	void (*pfnOSMODEM_Func14)(void);
	void (*pfnOSMODEM_Func15)(void);
	void (*pfnOSMODEM_Func16)(void);
	void (*pfnOSMODEM_Func17)(void);
	void (*pfnOSMODEM_Func18)(void);
	void (*pfnOSMODEM_Func19)(void);
	void (*pfnOSMODEM_Func20)(void);
	void (*pfnOSMODEM_Func21)(void);
	void (*pfnOSMODEM_Func22)(void);
	void (*pfnOSMODEM_Func23)(void);
	/* GSM Function */
	void (*pfnOSGSM_GprsControlInit)(unsigned char ucCtrl);
    unsigned char (*pfnOSGSM_GprsDial)(void);
    unsigned char (*pfnOSGSM_GprsCheckDial)(unsigned short uiTimeout);
    unsigned char (*pfnOSGSM_GprsHangupDial)(void);
    unsigned char (*pfnOSGSM_GprsReset)(void);
	unsigned char (*pfnOSGSM_GprsGetCCID)(unsigned char* pucCCID,unsigned char* pucCCIDLen);
	unsigned char (*pfnOSGSM_GprsSetAPN)(unsigned char* pucPtr);
	unsigned char (*pfnOSGSM_ShortMsgStat)(unsigned char* pucPtr);
	unsigned char (*pfnOSGSM_ShortMsgSend)(unsigned char* pucNum,unsigned char* pucMsg);
	unsigned char (*pfnOSGSM_ShortMsgRecv)(unsigned char ucIndex,unsigned char* pucPtr,unsigned short* uiLen);
	unsigned char (*pfnOSGSM_ShortMsgDele)(unsigned char ucNumber);
	unsigned char (*pfnOSGSM_GprsSetDialParam)(WIRELESS_PARAM wl);
	unsigned char (*pfnOSGSM_PhoneDial)(unsigned char *pucDialNum);
	unsigned char (*pfnOSGSM_AnswerCall)(void);
	unsigned char (*pfnOSGSM_PhoneHangup)(void);
	unsigned char (*pfnOSGSM_CheckCallComing)(unsigned char *pucTeleNums);
	unsigned char (*pfnOSGSM_DTMF)(unsigned char ucKey);
	unsigned char (*pfnOSGSM_PhoneCheckOnline)(void);
	void (*pfnOSMODEM_Func42)(void);
	void (*pfnOSMODEM_Func43)(void);
	void (*pfnOSMODEM_Func44)(void);
	void (*pfnOSMODEM_Func45)(void);
	void (*pfnOSMODEM_Func46)(void);
	void (*pfnOSMODEM_Func47)(void);
	void (*pfnOSMODEM_Func48)(void);
	void (*pfnOSMODEM_Func49)(void);
	/* Date&Time Function: */
	void (*pfnOSDATE_ReadDate)(unsigned char *pucDate);
	unsigned char (*pfnOSDATE_WriteDate)(unsigned char *pucDate);
	void (*pfnOSDATE_ReadTime)(unsigned char *pucTime);
	unsigned char (*pfnOSDATE_WriteTime)(unsigned char *pucTime);
	void (*pfnOSDATE_ReadTimeSec)(unsigned char *pucTime);
	void (*pfnOSDATE_ReadDateTime)(unsigned char *pucDateTime);
	void (*pfnOSDATE_ReadDateFormat)(unsigned char *pucDate);
	void (*pfnOSDATE_ReadTimeFormat)(unsigned char *pucTime);
	void (*pfnOSDATE_Func00)(void);
	void (*pfnOSDATE_Func01)(void);
	void (*pfnOSDATE_Func02)(void);
	void (*pfnOSDATE_Func03)(void);
	void (*pfnOSDATE_Func04)(void);
	void (*pfnOSDATE_Func05)(void);
	void (*pfnOSDATE_Func06)(void);
	void (*pfnOSDATE_Func07)(void);
	void (*pfnOSDATE_Func08)(void);
	void (*pfnOSDATE_Func09)(void);
	void (*pfnOSDATE_Func10)(void);
	void (*pfnOSDATE_Func11)(void);
	void (*pfnOSDATE_Func12)(void);
	void (*pfnOSDATE_Func13)(void);
	void (*pfnOSDATE_Func14)(void);
	void (*pfnOSDATE_Func15)(void);
	void (*pfnOSDATE_Func16)(void);
	void (*pfnOSDATE_Func17)(void);
	void (*pfnOSDATE_Func18)(void);
	void (*pfnOSDATE_Func19)(void);
	void (*pfnOSDATE_Func20)(void);
	void (*pfnOSDATE_Func21)(void);
	void (*pfnOSDATE_Func22)(void);
	void (*pfnOSDATE_Func23)(void);
	void (*pfnOSDATE_Func24)(void);
	void (*pfnOSDATE_Func25)(void);
	void (*pfnOSDATE_Func26)(void);
	void (*pfnOSDATE_Func27)(void);
	void (*pfnOSDATE_Func28)(void);
	void (*pfnOSDATE_Func29)(void);
	void (*pfnOSDATE_Func30)(void);
	void (*pfnOSDATE_Func31)(void);
	void (*pfnOSDATE_Func32)(void);
	void (*pfnOSDATE_Func33)(void);
	void (*pfnOSDATE_Func34)(void);
	void (*pfnOSDATE_Func35)(void);
	void (*pfnOSDATE_Func36)(void);
	void (*pfnOSDATE_Func37)(void);
	void (*pfnOSDATE_Func38)(void);
	void (*pfnOSDATE_Func39)(void);
	void (*pfnOSDATE_Func40)(void);
	void (*pfnOSDATE_Func41)(void);
	void (*pfnOSDATE_Func42)(void);
	void (*pfnOSDATE_Func43)(void);
	void (*pfnOSDATE_Func44)(void);
	void (*pfnOSDATE_Func45)(void);
	void (*pfnOSDATE_Func46)(void);
	void (*pfnOSDATE_Func47)(void);
	void (*pfnOSDATE_Func48)(void);
	void (*pfnOSDATE_Func49)(void);
	/* Timer Function: 3 */
	unsigned char (*pfnOSTIMER_Start)(unsigned int *puiTimer);
	void (*pfnOSTIMER_Stop)(unsigned int *puiTimer);
	unsigned char (*pfnOSTIMER_Delay)(unsigned int uiTimeout);
	void (*pfnOSTIMER_Func00)(void);
	void (*pfnOSTIMER_Func01)(void);
	void (*pfnOSTIMER_Func02)(void);
	void (*pfnOSTIMER_Func03)(void);
	void (*pfnOSTIMER_Func04)(void);
	void (*pfnOSTIMER_Func05)(void);
	void (*pfnOSTIMER_Func06)(void);
	void (*pfnOSTIMER_Func07)(void);
	void (*pfnOSTIMER_Func08)(void);
	void (*pfnOSTIMER_Func09)(void);
	void (*pfnOSTIMER_Func10)(void);
	void (*pfnOSTIMER_Func11)(void);
	void (*pfnOSTIMER_Func12)(void);
	void (*pfnOSTIMER_Func13)(void);
	void (*pfnOSTIMER_Func14)(void);
	void (*pfnOSTIMER_Func15)(void);
	void (*pfnOSTIMER_Func16)(void);
	void (*pfnOSTIMER_Func17)(void);
	void (*pfnOSTIMER_Func18)(void);
	void (*pfnOSTIMER_Func19)(void);
	void (*pfnOSTIMER_Func20)(void);
	void (*pfnOSTIMER_Func21)(void);
	void (*pfnOSTIMER_Func22)(void);
	void (*pfnOSTIMER_Func23)(void);
	void (*pfnOSTIMER_Func24)(void);
	void (*pfnOSTIMER_Func25)(void);
	void (*pfnOSTIMER_Func26)(void);
	void (*pfnOSTIMER_Func27)(void);
	void (*pfnOSTIMER_Func28)(void);
	void (*pfnOSTIMER_Func29)(void);
	void (*pfnOSTIMER_Func30)(void);
	void (*pfnOSTIMER_Func31)(void);
	void (*pfnOSTIMER_Func32)(void);
	void (*pfnOSTIMER_Func33)(void);
	void (*pfnOSTIMER_Func34)(void);
	void (*pfnOSTIMER_Func35)(void);
	void (*pfnOSTIMER_Func36)(void);
	void (*pfnOSTIMER_Func37)(void);
	void (*pfnOSTIMER_Func38)(void);
	void (*pfnOSTIMER_Func39)(void);
	void (*pfnOSTIMER_Func40)(void);
	void (*pfnOSTIMER_Func41)(void);
	void (*pfnOSTIMER_Func42)(void);
	void (*pfnOSTIMER_Func43)(void);
	void (*pfnOSTIMER_Func44)(void);
	void (*pfnOSTIMER_Func45)(void);
	void (*pfnOSTIMER_Func46)(void);
	void (*pfnOSTIMER_Func47)(void);
	void (*pfnOSTIMER_Func48)(void);
	void (*pfnOSTIMER_Func49)(void);
	/* Protected Memory */
	unsigned char (*pfnOSSAVE_Swap)(unsigned char ucPageNb);
	void (*pfnOSSAVE_Copy)(unsigned char *pucSrc, unsigned char *pucDest, unsigned short uiLen);
	void (*pfnOSSAVE_Set)(unsigned char *pucDest, unsigned char ucCh, unsigned short uiLen);
	unsigned char (*pfnOSSAVE_ReadEEPROM)(unsigned short uiStartAddr, unsigned char ucLen, unsigned char *pucPtr);
	/* GSM */
	void (*pfnOSGSM_Func00)(void);
	void (*pfnOSGSM_Func01)(void);
	void (*pfnOSGSM_Func02)(void);
	void (*pfnOSGSM_Func03)(void);
	void (*pfnOSGSM_Func04)(void);
	void (*pfnOSGSM_Func05)(void);
	void (*pfnOSGSM_Func06)(void);
	void (*pfnOSGSM_Func07)(void);
	void (*pfnOSGSM_Func08)(void);
	void (*pfnOSGSM_Func09)(void);
	void (*pfnOSGSM_Func10)(void);
	void (*pfnOSGSM_Func11)(void);
	void (*pfnOSGSM_Func12)(void);
	void (*pfnOSGSM_Func13)(void);
	void (*pfnOSGSM_Func14)(void);
	void (*pfnOSGSM_Func15)(void);
	void (*pfnOSGSM_Func16)(void);
	void (*pfnOSGSM_Func17)(void);
	void (*pfnOSGSM_Func18)(void);
	void (*pfnOSGSM_Func19)(void);
	void (*pfnOSGSM_Func20)(void);
	void (*pfnOSGSM_Func21)(void);
	void (*pfnOSGSM_Func22)(void);
	void (*pfnOSGSM_Func23)(void);
	void (*pfnOSGSM_Func24)(void);
	void (*pfnOSGSM_Func25)(void);
	void (*pfnOSGSM_Func26)(void);
	void (*pfnOSGSM_Func27)(void);
	void (*pfnOSGSM_Func28)(void);
	void (*pfnOSGSM_Func29)(void);
	void (*pfnOSGSM_Func30)(void);
	void (*pfnOSGSM_Func31)(void);
	void (*pfnOSGSM_Func32)(void);
	void (*pfnOSGSM_Func33)(void);
	void (*pfnOSGSM_Func34)(void);
	void (*pfnOSGSM_Func35)(void);
	void (*pfnOSGSM_Func36)(void);
	void (*pfnOSGSM_Func37)(void);
	void (*pfnOSGSM_Func38)(void);
	void (*pfnOSGSM_Func39)(void);
	void (*pfnOSGSM_Func40)(void);
	void (*pfnOSGSM_Func41)(void);
	void (*pfnOSGSM_Func42)(void);
	void (*pfnOSGSM_Func43)(void);
	void (*pfnOSGSM_Func44)(void);
	void (*pfnOSGSM_Func45)(void);
	void (*pfnOSGSM_Func46)(void);
	void (*pfnOSGSM_Func47)(void);
	void (*pfnOSGSM_Func48)(void);
	void (*pfnOSGSM_Func49)(void);
	/* OS Function ... */
    unsigned char (*pfnTCP_Open)(int *piTCPHandle);
    unsigned char (*pfnTCP_Connect)(int iTCPHandle,unsigned long ulPeerAddr,unsigned short uiPeerPort);
    unsigned char (*pfnTCP_Send)(int iTCPHandle,unsigned char *pucInBuf,unsigned short uiInLen);
    unsigned char (*pfnTCP_Recv)(int iTCPHandle,unsigned char *pucInBuf,unsigned short *puiInLen,unsigned short uiTimeout);
    unsigned char (*pfnTCP_Close)(int iTCPHandle);
	void (*pfnOSFUNC_Func05)(void);
	void (*pfnOSFUNC_Func06)(void);
	void (*pfnOSFUNC_Func07)(void);
	void (*pfnOSFUNC_Func08)(void);
	void (*pfnOSFUNC_Func09)(void);
	unsigned char (*pfnUDP_Open)(int *piUDPHandle);
	unsigned char (*pfnUDP_Config)(int iUDPHandle,unsigned long ulPeerAddr,unsigned short uiPeerPort);
 	unsigned char (*pfnUDP_Send)(int iUDPHandle,unsigned char *pucInBuf,unsigned short uiInLen);
 	unsigned char (*pfnUDP_Recv)(int iUDPHandle,unsigned char *pucInBuf,unsigned short *puiInLen,unsigned short uiTimeout);
 	unsigned char (*pfnUDP_Close)(int iUDPHandle);
	void (*pfnOSFUNC_Func15)(void);
	void (*pfnOSFUNC_Func16)(void);
	void (*pfnOSFUNC_Func17)(void);
	void (*pfnOSFUNC_Func18)(void);
	void (*pfnOSFUNC_Func19)(void);
	void (*pfnOSFUNC_Func20)(void);
	/* MIFARE Function: */
	MIFARE_ANSWER* (*pfnOSMIFARE_command)( MIFIRE_ORDER *pOrder );
	DRV_OUT* (*pfnOSMIFARE_Request)(unsigned char ucCardType,unsigned char ucReqMode);
	DRV_OUT* (*pfnOSMIFARE_Polling)(void);
	unsigned char (*pfnOSMIFARE_Active)(void);
	unsigned char (*pfnOSMIFARE_Anti)( unsigned char ucAntiEn,unsigned char *pucCardId,unsigned char *pucCardIdLen,unsigned char *pucCardClass );
	unsigned char (*pfnOSMIFARE_Select)( unsigned char *pucCardID,unsigned char ucCardIDLen,unsigned char *pucCardClass );
	unsigned char (*pfnOSMIFARE_Auth)( unsigned char ucAuthType,unsigned char ucSectorIndex,unsigned char ucKeyType,
				unsigned char *pucKey );
	unsigned char (*pfnOSMIFARE_SendData)( unsigned char ucCheckMode,unsigned char *pucSendData,unsigned int uiSendLen );
	unsigned char (*pfnOSMIFARE_SendRevFrame)( unsigned char *pucSendFrame,unsigned int uiSendLen,
								unsigned char *pucRevFrame,unsigned int *puiRevLen,unsigned int uiTimeDelay );
	unsigned char (*pfnOSMIFARE_DeSelect)(void);
	unsigned char (*pfnOSMIFARE_Halt)(void);
	unsigned char (*pfnOSMIFARE_Remove)(void);
	unsigned char (*pfnOSMIFARE_PowerRF)(unsigned char ucOnOff);
	void (*pfnOSFUNC_Func34)(void);
	unsigned char (*pfnDNS_StdQuery)(unsigned char* pQName,unsigned int *pauiHostIP,unsigned char* pucHostIPNum);
	void (*pfnOSFUNC_Func36)(void);
	void (*pfnOSFUNC_Func37)(void);
	void (*pfnOSFUNC_Func38)(void);
	void (*pfnOSFUNC_Func39)(void);
	/* WIFI Function */
	unsigned char (*pfnOSWIFI_Init)(POSWIFICFG pOSWIFICfg);
	unsigned char (*pfnOSWIFI_ParamConfig)(PWIFIPARAMCFG	pWIFIParamCfg);
	unsigned char (*pfnOSWIFI_NetConfig)(PWIFINETCFG  pWIFIConfig);
	unsigned char (*pfnOSWIFI_Connect)(ULONG ulPeerAddr,USHORT uiPeerPort,UINT uiTimeOut);
	unsigned char (*pfnOSWIFI_Send)(UCHAR *pucInBuf,USHORT uiInLen);
	unsigned char (*pfnOSWIFI_Recv)(UCHAR *pucBuf,USHORT* puiInLen,UINT uiTimeout);
	unsigned char (*pfnOSWIFI_Close)(void);
	void (*pfnOSFUNC_Func47)(void);
	void (*pfnOSFUNC_Func48)(void);
	void (*pfnOSFUNC_Func49)(void);
	void (*pfnOSFUNC_Func50)(void);
	void (*pfnOSFUNC_Func51)(void);
	void (*pfnOSFUNC_Func52)(void);
	void (*pfnOSFUNC_Func53)(void);
	void (*pfnOSFUNC_Func54)(void);
	void (*pfnOSFUNC_Func55)(void);
	void (*pfnOSFUNC_Func56)(void);
	void (*pfnOSFUNC_Func57)(void);
	void (*pfnOSFUNC_Func58)(void);
	void (*pfnOSFUNC_Func59)(void);
	void (*pfnOSFUNC_Func60)(void);
	void (*pfnOSFUNC_Func61)(void);
	void (*pfnOSFUNC_Func62)(void);
	void (*pfnOSFUNC_Func63)(void);
	void (*pfnOSFUNC_Func64)(void);
	void (*pfnOSFUNC_Func65)(void);
	void (*pfnOSFUNC_Func66)(void);
	void (*pfnOSFUNC_Func67)(void);
	void (*pfnOSFUNC_Func68)(void);
	void (*pfnOSFUNC_Func69)(void);
	void (*pfnOSFUNC_Func70)(void);
	void (*pfnOSFUNC_Func71)(void);
	void (*pfnOSFUNC_Func72)(void);
	void (*pfnOSFUNC_Func73)(void);
	void (*pfnOSFUNC_Func74)(void);
	void (*pfnOSFUNC_Func75)(void);
	void (*pfnOSFUNC_Func76)(void);
	void (*pfnOSFUNC_Func77)(void);
	void (*pfnOSFUNC_Func78)(void);
	void (*pfnOSFUNC_Func79)(void);
	void (*pfnOSFUNC_Func80)(void);
	void (*pfnOSFUNC_Func81)(void);
	void (*pfnOSFUNC_Func82)(void);
	void (*pfnOSFUNC_Func83)(void);
	void (*pfnOSFUNC_Func84)(void);
	void (*pfnOSFUNC_Func85)(void);
	void (*pfnOSFUNC_Func86)(void);
	void (*pfnOSFUNC_Func87)(void);
	void (*pfnOSFUNC_Func88)(void);
	void (*pfnOSFUNC_Func89)(void);
	void (*pfnOSFUNC_Func90)(void);
	void (*pfnOSFUNC_Func91)(void);
	void (*pfnOSFUNC_Func92)(void);
	void (*pfnOSFUNC_Func93)(void);
	void (*pfnOSFUNC_Func94)(void);
	void (*pfnOSFUNC_Func95)(void);
	void (*pfnOSFUNC_Func96)(void);
	void (*pfnOSFUNC_Func97)(void);
	void (*pfnOSFUNC_Func98)(void);
	void (*pfnOSFUNC_Func99)(void);
	/* Debug */
	unsigned char (*pfnOSDEBUG_Output)(char *pcStr);
	void (*pfnOSDEBUG_Printf)(char *pcFmt,...);
	void (*pfnOSDEBUG_Func01)(void);
	void (*pfnOSDEBUG_Func02)(void);
	void (*pfnOSDEBUG_Func03)(void);
	void (*pfnOSDEBUG_Func04)(void);
	void (*pfnOSDEBUG_Func05)(void);
	void (*pfnOSDEBUG_Func06)(void);
	void (*pfnOSDEBUG_Func07)(void);
	void (*pfnOSDEBUG_Func08)(void);
	void (*pfnOSDEBUG_Func09)(void);
	/* File Function */
    int (*pfnOSAPP_OpenFile)(char *pcFileName,unsigned char ucMode);
    int (*pfnOSAPP_OpenFileEx)(char *pcFileName,unsigned char ucMode,unsigned char *pucAttr);
    int (*pfnOSAPP_FileRead)(int iHandle,unsigned char *pucOutData,unsigned int uiOutLen);
    int (*pfnOSAPP_FileWrite)(int iHandle,unsigned char *pucInData,unsigned int uiInLen);
    int (*pfnOSAPP_FileClose)(int iHandle);
    int (*pfnOSAPP_FileSeek)(int iHandle,long ulOffset,unsigned char ucLocation);
    long (*pfnOSAPP_FileSize)(char *pcFileName);
    int (*pfnOSAPP_FileDelete)(char *pcFileName);
    int (*pfnOSAPP_FileTrunc)(int iHandle,unsigned int uiLen);
	unsigned char (*pfnOSAPP_FileGetLastError)(void);
	void (*pfnFunc10)(void);
	void (*pfnFunc11)(void);
	void (*pfnFunc12)(void);
	void (*pfnOSAPP_ChangeName)(unsigned char *pucName);
	void (*pfnFunc14)(void);
	void (*pfnFunc15)(void);
	void (*pfnFunc16)(void);
	void (*pfnFunc17)(void);
	void (*pfnFunc18)(void);
	void (*pfnFunc19)(void);
    /* C Function */
    void *(*pfnOSMEM_Memcpy)(void *pvDest,const void *pvSrc,unsigned int uiLen);
    int (*pfnOSMEM_Memcmp)(const void *pvDest, const void *pvSrc,unsigned int uiLen);
    void *(*pfnOSMEM_Memset)(void *pvDest,int iValue,unsigned int uiLen);
    char *(*pfnOSMEM_Strcpy)(char *pcDest,const char *pcSrc);
    char *(*pfnOSMEM_Strncpy)(char *pcDest,const char *pcSrc,unsigned int uiLen);
    int (*pfnOSMEM_Strcmp)(const char *pcDest,const char *pcSrc);
    int (*pfnOSMEM_Strncmp)(const char *pcDest,const char *pcSrc,unsigned int uiLen);
    char *(*pfnOSMEM_Strcat)(char * pcDest,const char *pcSrc);
    char *(*pfnOSMEM_Strncat)(char * pcDest,const char *pcSrc,unsigned int uiLen);
    unsigned int (*pfnOSMEM_Strlen)(const char * pcPtr);
	void (*pfnFunc30)(void);
	void (*pfnFunc31)(void);
	void (*pfnFunc32)(void);
	void (*pfnFunc33)(void);
	void (*pfnFunc34)(void);
	void (*pfnFunc35)(void);
	void (*pfnFunc36)(void);
	void (*pfnFunc37)(void);
	void (*pfnFunc38)(void);
	void (*pfnFunc39)(void);
	unsigned char (*pfnOSIR_SendBuf)(unsigned char ucModuleID,unsigned int uiWaitTime,unsigned char *pSendBuf,unsigned int uiSendLen);
	unsigned char (*pfnOSIR_Receive)(unsigned char ucModuleID,unsigned int uiWaitTime,unsigned char *pRevBuf,unsigned int *puiRevLen );
	unsigned char (*pfnOSIR_SendReceive)(unsigned char ucModuleID,unsigned int uiWaitTime,unsigned char *pSendBuf,unsigned int uiSendLen,unsigned char *pRevBuf,unsigned int *puiRevLen );
	void (*pfnFunc43)(void);
	void (*pfnFunc44)(void);
	void (*pfnFunc45)(void);
	void (*pfnFunc46)(void);
	void (*pfnFunc47)(void);
	void (*pfnFunc48)(void);
	void (*pfnFunc49)(void);
	unsigned char (*pfnOSMOBILE_CheckBase)(void);
	void (*pfnOSMOBILE_PowerOff)(void);
	void (*pfnOSMOBILE_GetBatterLevel)(unsigned int *puiValue);
	void (*pfnFunc53)(void);
	void (*pfnFunc54)(void);
	void (*pfnFunc55)(void);
	void (*pfnFunc56)(void);
	void (*pfnFunc57)(void);
	void (*pfnFunc58)(void);
	void (*pfnFunc59)(void);
	void (*pfnFunc60)(void);
	void (*pfnFunc61)(void);
	void (*pfnFunc62)(void);
	unsigned char (*pfnOSBARCODE_EANPrint)(unsigned char *pucData);
	void (*pfnFunc64)(void);
	void (*pfnFunc65)(void);
	void (*pfnFunc66)(void);
	unsigned char (*pfnOSTMS_HostConnect)(unsigned char ucType,unsigned char *pucPtr,unsigned short *puiLen);
	unsigned char (*pfnOSTMS_GetCardNumber)(void);
	unsigned char (*pfnOSTMS_Save_File)(unsigned char ucType,unsigned char ucFlag,unsigned long ulAppSize);
	void (*pfnFunc70)(void);
	void (*pfnFunc71)(void);
	void (*pfnFunc72)(void);
	void (*pfnFunc73)(void);
	void (*pfnFunc74)(void);
	void (*pfnFunc75)(void);
	void (*pfnFunc76)(void);
	void (*pfnFunc77)(void);
	void (*pfnFunc78)(void);
	void (*pfnFunc79)(void);
	void (*pfnFunc80)(void);
	void (*pfnFunc81)(void);
	void (*pfnFunc82)(void);
	void (*pfnFunc83)(void);
	void (*pfnFunc84)(void);
	void (*pfnFunc85)(void);
	void (*pfnFunc86)(void);
	void (*pfnFunc87)(void);
	void (*pfnFunc88)(void);
	void (*pfnFunc89)(void);
	void (*pfnFunc90)(void);
	void (*pfnFunc91)(void);
	void (*pfnFunc92)(void);
	void (*pfnFunc93)(void);
	void (*pfnFunc94)(void);
	void (*pfnFunc95)(void);
	void (*pfnFunc96)(void);
	unsigned char (*pfnOSAPP_MenuDisplay)(unsigned char ucMenuCurrPage);
	unsigned char (*pfnOSAPP_EventSelect)(unsigned char ucKey,OSEVENT *pEvent);
	unsigned char (*pfnOSAPP_EventRun)(OSEVENT *pEvent);
	unsigned short uiCRC;
}OSAPI;




#ifdef __cplusplus
}
#endif

#endif

